### PR TITLE
Added back the capitalization for constants

### PR DESCRIPTION
**Pull request by dostertag**
Hopefully i pulled the right way this time.  I did it incorrectly the first time and couldn't re-sync my branch (or just couldn't figure out how to).  Thanks for your patience!!

### CODE REVIEW

**Comment by CoreyHendrey** [comment]
I did a similar thing and it cost me a couple hours trying to sync them back up haha.
http://www.ocpsoft.org/tutorials/git/reset-and-sync-local-respository-with-remote-branch/

This worked for me in the end :)

**Comment by CoreyHendrey** [comment]
The only thing I'd note is that one of your commits seems to have deleted an entire file, and then rewrite it. Are you using the terminal to use git, or something like SourceTree?

**Comment by dostertag** [comment]
terminal only, until pull.  To pull, I go to my repo on github, then pull to here....  

otherwise in terminal to merge with origin/master.

**Comment by dostertag** [comment]
Not sure why the player class seemed to be deleted then added... I only searched through the player class and replaced constants with their new case....

**Comment by CoreyHendrey** [comment]
Not sure, it's not big deal :) My SourceTree does it sometimes too. No idea why, haha.

**Pull request merged**
