### PR TITLE
Fixed collision issue. Still a small bug if movement is sporadic

### PR DESCRIPTION
**Pull request by StewartWallace1115**
Fixed collision issue. Still a small bug if movement is sporadic.

### CODE REVIEW

**Comment by StewartWallace1115** [comment]
I messed up the Wall class I fixed in my second commit.

**Comment by ashish2199** [comment]
What you are doing is respawn the player back into the game, when it hits the wall. 
Right ? If this is correct then I would advice you to make a function for it so that it can be called only when needed.
Also when I tried view your code, your repo seems to be a bit behind as compared to this repo as there were other changes too.

**Comment by StewartWallace1115** [comment]
Is the player suppose to die when he hits the wall? I thought he was supposed to "glide" along the wall.

**Comment by ashish2199** [comment]
Actually no the player isn't supposed to hit the wall. In the real game he is supposed to not go over the walls.
But at the time being I wanted to implement that so that we could see if the collision detection is working correctly and also it will be used in future when we introduce enemies into the game. I wanted see how we are going to implement that first as it will determine how other code will be made.

And for the pull request make it function like respawn(int steps,Direction direction) I will merge it when you do that.

**Pull request closed without merging**
