### PR TITLE
Added Entity Vector to GameVariables

### PR DESCRIPTION
**Pull request by CoreyHendrey**
All Entities are now to be added to GameVariables

The GameLoop then goes down the list of current entities and calls their draw() functions.
```
         for(Entity e : GameVariables.getEntities())
                	e.draw();
```

Initalize objects in the scene, like so:

```
        //Initialize Objects
        Player p = new Player();
        Player p2 = new Player();
        p2.positionX = 300;
        p2.positionY = 100;

        GameVariables.addEntityToGame(p);
        GameVariables.addEntityToGame(p2);
```

### CODE REVIEW

**Comment by ashish2199** [comment]
I feel scene classes like sandbox  should have list of entities as entities belong to a scene.

Gamevariables class is for having variables related to game. Like which level the player is on, Score , things and other such similar things.

**Comment by CoreyHendrey** [comment]
Sure that seems logical to me too

**Comment by CoreyHendrey** [comment]
Changed them.

**Comment by ashish2199** [comment]
Merged along with some changes to resolve conflict. Now Sandbox class will have a reference of player also. I dont see use of more than one player now as we will mostly be working towards a single player game. If in future we plan to make game multiplayer, we will have a array of players instead with the scene.

**Comment by CoreyHendrey** [comment]
Sounds good :)

**Pull request merged**
